spring.profiles.active=test

spring.application.name=customer

server.port=8083
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/.well-known/jwks.json