spring.application.name=customer
spring.profiles.active=docker-test

server.port=8083
logging.level.org.springframework.security=DEBUG

# Resource server configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authorization-service:8081/.well-known/jwks.json